version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
